"""Collect sanitized local files into a failure artifact dictionary."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

KNOWN_FILES = {
    "error_log": "error.log",
    "html_snapshot": "snapshot.html",
    "screenshot": "screenshot.png",
    "network_log": "network.json",
    "console_log": "console.log",
    "expected_schema": "expected_schema.json",
    "actual_output": "actual_output.json",
    "notes": "notes.md",
}


def collect_from_dir(input_dir: Path | str, tool: str = "unknown") -> dict:
    root = Path(input_dir)
    refs = {
        key: filename
        for key, filename in KNOWN_FILES.items()
        if (root / filename).exists()
    }
    return {
        "schema_version": "failure-artifact/v1",
        "run_id": f"collected_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}",
        "tool": tool,
        "target_type": "sanitized_real_failure",
        "summary": "Collected sanitized failure pack",
        "error": {
            "message": (root / "error.log").read_text(encoding="utf-8", errors="replace")[:500] if (root / "error.log").exists() else "",
            "stack": "",
            "status_code": None,
        },
        "artifacts": refs,
        "observations": {},
        "expected": {"required_fields": []},
        "actual": {"fields": {}, "array_length": None},
        "labels": {"failure_type": "unknown", "confidence": 0.0},
        "safety": {
            "sanitized": True,
            "contains_credentials": False,
            "external_network_required": False,
            "user_authorized_or_synthetic": True,
            "redaction_notes": "Generated by warb collect; user is responsible for pre-sanitizing files.",
        },
    }
