"""Create a sanitized shareable failure pack from a local failed run directory."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable
from zipfile import ZIP_DEFLATED, ZipFile

from .classifier import classify_failure_artifact
from .reporter import render_markdown_report

PACK_FILES = {
    "error_log": "error.log",
    "html_snapshot": "snapshot.html",
    "screenshot": "screenshot.png",
    "network_log": "network.json",
    "console_log": "console.log",
    "expected_schema": "expected_schema.json",
    "actual_output": "actual_output.json",
    "notes": "notes.md",
}

TEXT_SUFFIXES = {".html", ".json", ".log", ".md", ".txt", ".csv", ".xml", ".yaml", ".yml"}

REDACTION_PATTERNS = (
    (re.compile(r"(?i)(authorization\s*:\s*bearer\s+)[^\s\"']+"), r"\1[REDACTED]"),
    (re.compile(r"(?i)(authorization\s*:\s*)[^\r\n]+"), r"\1[REDACTED]"),
    (re.compile(r"(?i)(cookie\s*:\s*)[^\r\n]+"), r"\1[REDACTED]"),
    (re.compile(r"(?i)(set-cookie\s*:\s*)[^\r\n]+"), r"\1[REDACTED]"),
    (re.compile(r"(?i)(sessionid|session|token|access_token|refresh_token|api_key|apikey|password)(['\"]?\s*[:=]\s*['\"]?)[^'\"\s,;<>]+"), r"\1\2[REDACTED]"),
    (re.compile(r"(?i)(value\s*=\s*['\"])[^'\"]*(['\"])"), r"\1[REDACTED]\2"),
)


def sanitize_text(text: str) -> str:
    sanitized = text
    for pattern, replacement in REDACTION_PATTERNS:
        sanitized = pattern.sub(replacement, sanitized)
    return sanitized


def package_failure_dir(
    input_dir: Path | str,
    out_dir: Path | str,
    *,
    tool: str = "unknown",
    run_id: str | None = None,
    summary: str = "Collected sanitized failure pack",
    required_fields: Iterable[str] | None = None,
    status_code: int | None = None,
) -> dict[str, Any]:
    src = Path(input_dir)
    dst = Path(out_dir)
    if not src.exists():
        raise FileNotFoundError(f"input directory not found: {src}")
    if not src.is_dir():
        raise NotADirectoryError(f"input path is not a directory: {src}")

    dst.mkdir(parents=True, exist_ok=True)
    artifact_refs = _copy_known_files(src, dst)
    required = list(required_fields or _required_fields_from_schema(dst / "expected_schema.json"))
    actual_fields = _actual_fields_from_output(dst / "actual_output.json")
    error_message = _first_text(dst / "error.log", limit=500)

    artifact = {
        "schema_version": "failure-artifact/v1",
        "run_id": run_id or f"pack_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}",
        "tool": tool,
        "target_type": "sanitized_real_failure",
        "summary": summary,
        "error": {
            "message": error_message,
            "stack": "",
            "status_code": status_code,
        },
        "artifacts": artifact_refs,
        "observations": {
            "packaged_by": "warb pack",
            "source_files": sorted(artifact_refs.values()),
        },
        "expected": {"required_fields": required},
        "actual": {"fields": actual_fields, "array_length": _array_length_from_output(dst / "actual_output.json")},
        "labels": {"failure_type": "unknown", "confidence": 0.0},
        "safety": {
            "sanitized": True,
            "contains_credentials": False,
            "external_network_required": False,
            "user_authorized_or_synthetic": True,
            "redaction_notes": "Generated by warb pack using local text redaction rules; review before sharing.",
        },
    }
    diagnosis = classify_failure_artifact(artifact)
    artifact["labels"] = {
        "failure_type": diagnosis.get("failure_type", "unknown"),
        "confidence": diagnosis.get("confidence", 0.0),
    }

    artifact_path = dst / "failure_artifact.json"
    artifact_path.write_text(json.dumps(artifact, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    issue_path = dst / "github_issue.md"
    issue_path.write_text(_render_issue_body(artifact, diagnosis), encoding="utf-8")

    report_path = dst / "diagnosis.md"
    report_path.write_text(render_markdown_report(diagnosis, artifact), encoding="utf-8")

    zip_path = dst / "failure_pack.zip"
    _write_zip(dst, zip_path)

    return {
        "artifact_path": str(artifact_path),
        "issue_path": str(issue_path),
        "zip_path": str(zip_path),
        "diagnosis": diagnosis,
    }


def _copy_known_files(src: Path, dst: Path) -> dict[str, str]:
    refs: dict[str, str] = {}
    for key, filename in PACK_FILES.items():
        source = src / filename
        if not source.exists() or not source.is_file():
            continue
        target = dst / filename
        if source.suffix.lower() in TEXT_SUFFIXES:
            target.write_text(sanitize_text(source.read_text(encoding="utf-8", errors="replace")), encoding="utf-8")
        else:
            target.write_bytes(source.read_bytes())
        refs[key] = filename
    return refs


def _first_text(path: Path, *, limit: int) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")[:limit]


def _required_fields_from_schema(path: Path) -> list[str]:
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return []
    required = data.get("required") or data.get("required_fields") or []
    return [str(item) for item in required] if isinstance(required, list) else []


def _actual_fields_from_output(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    if isinstance(data, dict):
        return data
    if isinstance(data, list) and data and isinstance(data[0], dict):
        return data[0]
    return {}


def _array_length_from_output(path: Path) -> int | None:
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None
    return len(data) if isinstance(data, list) else None


def _render_issue_body(artifact: dict[str, Any], diagnosis: dict[str, Any]) -> str:
    evidence = "\n".join(f"- {item}" for item in diagnosis.get("evidence", [])) or "- No evidence extracted yet."
    fixes = "\n".join(f"- {item}" for item in diagnosis.get("suggested_fix", [])) or "- Needs maintainer triage."
    files = "\n".join(f"- `{path}`" for path in sorted(artifact.get("artifacts", {}).values())) or "- `failure_artifact.json`"
    return f"""# Failure Pack: {artifact.get("run_id")}

## Summary
{artifact.get("summary", "")}

## Initial Diagnosis
- Failure type: `{diagnosis.get("failure_type", "unknown")}`
- Confidence: `{diagnosis.get("confidence", 0.0)}`
- Tool: `{artifact.get("tool", "unknown")}`

## Evidence
{evidence}

## Suggested Fix Direction
{fixes}

## Included Files
{files}
- `failure_artifact.json`
- `diagnosis.md`

## Safety Checklist
- [x] Credentials, cookies, tokens, and passwords were redacted by `warb pack`.
- [ ] I reviewed the generated pack before sharing.
- [x] No CAPTCHA bypass or anti-bot evasion request is included.
"""


def _write_zip(root: Path, zip_path: Path) -> None:
    with ZipFile(zip_path, "w", ZIP_DEFLATED) as archive:
        for path in sorted(root.iterdir()):
            if path == zip_path or not path.is_file():
                continue
            archive.write(path, path.name)
